### ISSUE TITLE
Lack of image loading in preview cards

### ISSUE THREAD

**Issue by Fmstrat** [moneytoo/tt-rss-for-palabre#4]
Hi,

I understand you don't really use Palabre anymore, however I find its magazine layout is still the best out there for tablets. That being said there doesn't seem to be support from this plugin to display images in the preview cards.

Since I doubt you are actively working on this project, I'd like to do some investigation on my own. Could you point me in the right direction on how to compile/test on a device? I've never worked on a Palabre plugin before.

Thanks!

**Comment by moneytoo** [comment]
Publishing your changes to open beta track: https://play.google.com/apps/testing/com.brouken.palabre.ttrss

**Comment by Fmstrat** [comment]
Great news, thanks!
